name: anwerapp
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  carousel_pro:
  firebase_storage:
  firebase_database:
  firebase_core:
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  flutter_staggered_grid_view:
  firebase_messaging:
  flutter_local_notifications:
  flutter_launcher_icons:
  video_player:
  carousel_slider:
  flutter_sparkline:
  flutter_circular_chart:
  font_awesome_flutter:
  unicorndial:
  flutter_spinkit:
  shared_preferences:
  fluttertoast:
  url_launcher:
  audioplayers:
  image_picker:
  curved_navigation_bar:
  avatar_glow:
  flutter_search_bar:
  flutter_full_pdf_viewer:






#==============launcher_icon=====================
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "img/logoapp.png"

#==============launcher_icon=====================
dev_dependencies:
  flutter_test:
    sdk: flutter


#==============material=========================
flutter:
  uses-material-design: true


  #==============assets==========================
  assets:
    - img/Rabih.mp3
    - img/name.jpg
    - img/conference.png
    - img/female.jpg
    - img/delivery.png
    - img/route.png
    - img/poster/pro1.jpg
    - img/poster/pro2.jpg
    - img/poster/pro3.jpg
    - img/poster/pro4.jpg
    - img/poster/pro5.jpg
    - img/poster/pro6.jpg
    - img/poster/pro7.jpg
    - img/poster/pro8.jpg
    - img/desk.png
    - img/desks.png
    - img/dresser.png
    - img/dressers.png
    - img/appicon.png
    - img/Introducing.mp4
    - img/logoapp.png

#==========fonts===============================
  fonts:
       - family: Cairo
         fonts:
           - asset: fonts/Cairo-Regular.ttf